version: '3'
services:
  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./wordpress.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_logs:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - todolist-server
    networks:
      - todo_list_net

  todolist-server:
    image:  golang:1.13.0-alpine
    restart: always
    volumes:
      - .:/server
    networks:
      - todo_list_net
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    volumes:
      - ./docker/db/mongo:/data/db
    restart: always
    networks:
      - todo_list_net
  redis:
    image: redis:latest
    volumes:
      - ./docker/db/redis:/data
    restart: always
    networks:
      - todo_list_net

networks:
  todo_list_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24