// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiUserLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ValidateCode         string   `protobuf:"bytes,3,opt,name=validate_code,json=validateCode,proto3" json:"validate_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiUserLogin) Reset()         { *m = ApiUserLogin{} }
func (m *ApiUserLogin) String() string { return proto.CompactTextString(m) }
func (*ApiUserLogin) ProtoMessage()    {}
func (*ApiUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ApiUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserLogin.Unmarshal(m, b)
}
func (m *ApiUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserLogin.Marshal(b, m, deterministic)
}
func (m *ApiUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserLogin.Merge(m, src)
}
func (m *ApiUserLogin) XXX_Size() int {
	return xxx_messageInfo_ApiUserLogin.Size(m)
}
func (m *ApiUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserLogin proto.InternalMessageInfo

func (m *ApiUserLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ApiUserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ApiUserLogin) GetValidateCode() string {
	if m != nil {
		return m.ValidateCode
	}
	return ""
}

type ApiUserLoginResult struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiUserLoginResult) Reset()         { *m = ApiUserLoginResult{} }
func (m *ApiUserLoginResult) String() string { return proto.CompactTextString(m) }
func (*ApiUserLoginResult) ProtoMessage()    {}
func (*ApiUserLoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

func (m *ApiUserLoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserLoginResult.Unmarshal(m, b)
}
func (m *ApiUserLoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserLoginResult.Marshal(b, m, deterministic)
}
func (m *ApiUserLoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserLoginResult.Merge(m, src)
}
func (m *ApiUserLoginResult) XXX_Size() int {
	return xxx_messageInfo_ApiUserLoginResult.Size(m)
}
func (m *ApiUserLoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserLoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserLoginResult proto.InternalMessageInfo

func (m *ApiUserLoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiUserLogin)(nil), "protocol.ApiUserLogin")
	proto.RegisterType((*ApiUserLoginResult)(nil), "protocol.ApiUserLogin.result")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x52, 0xbc, 0xf9,
	0x05, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x09, 0xa5, 0x2f, 0x8c, 0x5c, 0x3c, 0x8e, 0x05, 0x99,
	0xa1, 0xc5, 0xa9, 0x45, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x42, 0x56, 0x5c, 0x1c, 0x20, 0x7d, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x4e, 0x72, 0xa7, 0x9e, 0xc8, 0x72, 0x3e,
	0x9f, 0xb2, 0xe2, 0x59, 0xc7, 0xf6, 0xa7, 0x13, 0x7a, 0x2f, 0x3d, 0x91, 0xe5, 0x75, 0x28, 0x2e,
	0x29, 0xca, 0xcc, 0x4b, 0x8f, 0x36, 0xd2, 0x31, 0x32, 0x88, 0x0d, 0x82, 0xab, 0x17, 0x32, 0xe7,
	0xe2, 0x28, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x02, 0xeb, 0x95, 0x3e, 0xf5,
	0x44, 0x96, 0xed, 0xe9, 0xfa, 0xb6, 0xe7, 0x0b, 0x1a, 0x91, 0x35, 0x5a, 0x40, 0x34, 0xc2, 0x14,
	0x0b, 0x19, 0x71, 0xf1, 0x96, 0x25, 0xe6, 0x64, 0xa6, 0x24, 0x96, 0xa4, 0xc6, 0x27, 0xe7, 0xa7,
	0xa4, 0x4a, 0x30, 0x83, 0x75, 0xf3, 0x82, 0x6c, 0x7e, 0xb9, 0xaa, 0xe7, 0xc5, 0xfa, 0xc6, 0xe7,
	0x0b, 0x1a, 0x83, 0x78, 0x60, 0x6a, 0x9c, 0xf3, 0x53, 0x52, 0xa5, 0xe4, 0xb8, 0xd8, 0x8a, 0x52,
	0x8b, 0x4b, 0x73, 0x4a, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0x20, 0xee, 0x0d,
	0x82, 0x70, 0xac, 0xa4, 0x4f, 0x7d, 0x96, 0x60, 0xd3, 0xcf, 0x01, 0x79, 0xea, 0x52, 0xf3, 0x4f,
	0x46, 0x1e, 0x88, 0x0f, 0x9e, 0xcf, 0xdc, 0xfd, 0x74, 0xef, 0xd4, 0x24, 0x36, 0xb0, 0xef, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x96, 0x7e, 0x49, 0x24, 0x01, 0x00, 0x00,
}
