// Code generated by go-easy generate-mongodb DO NOT EDIT.
// go-easy url: https://github.com/siskinc/go-easy
package db

import (
	"context"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"time"

	"fmt"
)

var _ = time.Now()
var ThemeContext = context.Background()

func (model *Theme) Save() (interface{}, error) {

	model.CreatedAt = time.Now().UTC()

	var count int64
	var err error

	model.ID = primitive.NewObjectID()

	OwnerAndNameFilter := bson.M{

		"owner": model.Owner,

		"name": model.Name,
	}
	count, err = todoItemCollection.CountDocuments(ThemeContext, OwnerAndNameFilter)
	if nil != err {
		return nil, err
	}
	if count > 0 {
		return nil, fmt.Errorf(" Owner = %s is exist  Name = %s is exist ",
			model.Owner, model.Name,
		)
	}

	result, err := todoItemCollection.InsertOne(ThemeContext, model)
	if nil != err {
		return nil, err
	}
	return result.InsertedID, err
}

func (model *Theme) Delete(filter interface{}) (int64, error) {
	result, err := todoItemCollection.DeleteMany(ThemeContext, filter)
	if nil != err {
		return 0, err
	}
	return result.DeletedCount, err
}

func (model *Theme) DeleteByID() (int64, error) {
	filter := bson.M{
		"_id": model.ID,
	}
	result, err := todoItemCollection.DeleteOne(ThemeContext, filter)
	if nil != err {
		return 0, err
	}
	return result.DeletedCount, err
}

func (model *Theme) FindByID() (err error) {
	filter := bson.M{
		"_id": model.ID,
	}

	result := todoItemCollection.FindOne(ThemeContext, filter)
	err = result.Decode(model)

	return
}

func (model *Theme) Find(filter interface{}) (err error) {

	result := todoItemCollection.FindOne(ThemeContext, filter)
	err = result.Decode(model)
	return
}

func (model *Theme) FindAll(filter interface{}) (modelList []Theme, err error) {

	var cursor *mongo.Cursor
	cursor, err = todoItemCollection.Find(ThemeContext, filter)
	for nil != cursor && cursor.Next(ThemeContext) {
		temp := Theme{}
		err = cursor.Decode(&temp)
		if nil != err {
			return
		}
		modelList = append(modelList, temp)
	}
	return
}

func (model *Theme) FindPage(filter interface{}, iPageSize, iPageIndex int64, SortedStrs ...string) (modelList []Theme, count int64, err error) {

	count, err = todoItemCollection.CountDocuments(ThemeContext, filter)
	if nil != err {
		return
	}
	opt := &options.FindOptions{}
	skip := iPageSize * (iPageIndex - 1)
	opt = opt.SetLimit(iPageSize).SetSkip(skip)
	for _, sortStr := range SortedStrs {
		opt = opt.SetSort(sortStr)
	}
	var cursor *mongo.Cursor
	cursor, err = todoItemCollection.Find(ThemeContext, filter, opt)
	for nil != cursor && cursor.Next(ThemeContext) {
		temp := Theme{}
		err = cursor.Decode(&temp)
		if nil != err {
			return
		}
		modelList = append(modelList, temp)
	}
	return
}

func (model *Theme) UpdateByID() (err error) {
	objectID := model.ID
	filter := bson.M{
		"_id": objectID,
	}

	model.UpdatedAt = time.Now().UTC()

	_, err = todoItemCollection.UpdateOne(ThemeContext, filter, model)
	return
}

func (model *Theme) Update(filter interface{}) (err error) {

	model.UpdatedAt = time.Now().UTC()

	_, err = todoItemCollection.UpdateMany(ThemeContext, filter, model)
	return
}

func (model *Theme) FindByOwnerAndName(owner primitive.ObjectID, name string) (err error) {
	filter := bson.M{

		"owner": owner,

		"name": name,
	}

	result := todoItemCollection.FindOne(ThemeContext, filter)
	err = result.Decode(model)

	return
}
