// Code generated by go-easy generate error code DO NOT EDIT.
// go-easy url: https://github.com/siskinc/go-easy
package errcode

func (e ResponseErrorCode) Error() string {
	switch e {

	case ResponseErrorCodeRePassword:
		return "输入的两次密码不一致"

	}
	return "UNKNOWN"
}

func (e ResponseErrorCode) String() string {
	switch e {

	case ResponseErrorCodeRePassword:
		return "ResponseErrorCodeRePassword"

	}
	return "UNKNOWN"
}

func (e ResponseErrorCode) ErrorCode() uint64 {
	return uint64(e)
}
